name: Testing my workflow file 1.2

on:
  push:
    branches:
      - ci-linux-android
    tags:
      - '*'

jobs:
  build-android:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install OpenJDK 11
        run: sudo apt-get update && sudo apt-get install -y openjdk-11-jdk

      - name: Set JAVA_HOME
        run: echo "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" | sudo tee -a /etc/environment

      - name: Print JAVA_HOME path
        run: echo $JAVA_HOME

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Create .env.local file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.local > android/local.properties

      - name: Setup branch and env 
        run: |
          # Strip git ref prefix from version
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV
