name: Integrating fastlane with pipeline

on:
  push:
    branches:
      - ci-linux-android
    tags:
      - '*'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install npm dependencies
        run: |
          npm install
      
      - name: Create .env.local file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.local > android/local.properties

      - name: Setup branch and env
        run: |
          # Strip git ref prefix from version
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV   

      - name: Setup branch and GPG public key
        run: |
          # Strip git ref prefix from version
        
          echo ${{ env.BRANCH_NAME }}
       
          echo ${{ env.GPG_TTY }}
          sudo apt-get --yes install gnupg2
          gpg2 --import ./.github/keys/mosipgpgkey_pub.gpg 
          gpg2 --quiet --batch --passphrase=${{secrets.gpg_secret}}  --allow-secret-key-import --import ./.github/keys/mosipgpgkey_sec.gpg

#1 - generate at runtime.
#2 - Encrypt in workflow and decrypt and use it.
      - name: Generate keystore
        run: |
          keytool \
          -genkey -v \
          -storetype PKCS12 \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass 'android' \
          -keypass 'android' \
          -alias androidreleasekey \
          -keystore android/app/release.keystore \
          -dname "CN=io.mosip.residentapp,OU=,O=,L=,S=,C=US"

      - name: Export variables
        run: |
          export RELEASE_KEYSTORE=release.keystore
          export RELEASE_KEYSTORE_ALIAS=androidreleasekey
          export RELEASE_KEYSTORE_PASSWORD=android  
          echo $RELEASE_KEYSTORE
          echo $RELEASE_KEYSTORE_ALIAS
          echo $RELEASE_KEYSTORE_PASSWORD

      - name: Run Fastlane
        run: |
          cd android
          yes | sudo fastlane increment_vc
          yes | sudo fastlane increment_vname
          fastlane build_android
      
        env:
          MIMOTO_HOST: ${{ github.event.inputs.backendServiceUrl }}
          FIREBASE_SECRET: ${{ secrets.GPG_SECRET }}
          APPLICATION_THEME: ${{ github.event.inputs.theme }}
