name: Integrating fastlane with pipeline

on:
  push:
    branches:
      - ci-linux-android
    tags:
      - '*'

jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.20.0'

      - name: Install npm 
        run: |
          rm -rf node_modules
          rm -rf /tmp/metro-*
          npm install

      # Cache stuff for faster build
      # - name: Cache local npm repository
      #   uses: actions/cache@v3.0.11
      #   with:
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     path: ~/.npm

      # - name: Cache local gradle repository
      #   uses: actions/cache@v3.0.11
      #   with:
      #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      #     path: |
      #       ~/.gradle/caches
      #       ~/.gradle/wrapper
      
      - name: Create .env.local file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.local > android/local.properties

      - name: Setup branch and env
        run: |
          # Strip git ref prefix from version
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV   

      - name: Setup branch and GPG public key
        run: |
          # Strip git ref prefix from version
        
          echo ${{ env.BRANCH_NAME }}
       
          echo ${{ env.GPG_TTY }}
          sudo apt-get --yes install gnupg2
          gpg2 --import ./.github/keys/mosipgpgkey_pub.gpg 
          gpg2 --quiet --batch --passphrase=${{secrets.gpg_secret}}  --allow-secret-key-import --import ./.github/keys/mosipgpgkey_sec.gpg

      - name: See the path and list the files
        run: |
          cd .github/keys
          ls
          pwd

      - name: Setup keystore
        run: |
          gpg2 --import ./.github/keys/public_key.gpg
          gpg2 --quiet --batch --passphrase=adityan.kannan410  --allow-secret-key-import --import ./.github/keys/secret_key.gpg
          cd android
          if [ ! -z "adityan.kannan410" ] && [ -f app/release.keystore.gpg ];then rm -f app/release.keystore;gpg2 --quiet --batch --passphrase=adityan.kannan410 --pinentry-mode loopback --decrypt --output app/release.keystore app/release.keystore.gpg;fi
          
      - name: Export variables
        run: |
          export RELEASE_KEYSTORE=release.keystore
          export RELEASE_KEYSTORE_ALIAS=androidreleasekey
          export RELEASE_KEYSTORE_PASSWORD=android  
          echo $RELEASE_KEYSTORE
          echo $RELEASE_KEYSTORE_ALIAS
          echo $RELEASE_KEYSTORE_PASSWORD
          echo $NODE_OPTIONS

      - name: Run Fastlane
        run: | 
          cd android
          node -v  
          which node
          echo $PATH
          yes | sudo gem install bundler
          yes | sudo fastlane install_plugins
          fastlane build_android
          node -v
      
        env:
          MIMOTO_HOST: ${{ github.event.inputs.backendServiceUrl }}
          FIREBASE_SECRET: ${{ secrets.GPG_SECRET }}
          APPLICATION_THEME: ${{ github.event.inputs.theme }}
