name: Upload to Play store - MOSIP Resident Application

env:
  backendServiceDefaultUrl: https://api.qatriple.mosip.net
on:
  workflow_dispatch:
    inputs:
      backendServiceUrl:
        description: 'Backend service URL'
        required: true
        default: 'https://api.qatriple.mosip.net'
        type: string
      theme:
        description: 'Application Theme'
        required: true
        default: 'orange'
        type: choice
        options:
          - orange
          - purple

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install npm 
        run: |
          npm install
      
      - name: Cache local npm repository
        uses: actions/cache@v3.0.11
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm

      - name: Cache local gradle repository
        uses: actions/cache@v3.0.11
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Create .env.local file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.local > android/local.properties

      - name: Setup branch and env
        run: |
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV   

      - name: Setup branch and GPG public key
        run: |
          sudo apt-get --yes install gnupg2
          gpg2 --import ./.github/keys/mosipgpgkey_pub.gpg 
          gpg2 --quiet --batch --passphrase=${{secrets.gpg_secret}}  --allow-secret-key-import --import ./.github/keys/mosipgpgkey_sec.gpg

      - name: Setup Firebase
        run: |
          cd android
          if [ ! -z "$FIREBASE_SECRET" ] && [ -f app/google-services.json.gpg ];then rm -f app/google-services.json;gpg2 --quiet --batch --passphrase=$FIREBASE_SECRET --pinentry-mode loopback --decrypt --output app/google-services.json app/mosip-google-services.json.gpg;fi
        env:
          FIREBASE_SECRET: ${{ secrets.GPG_SECRET }}

      - name: Generate keystore
        run: |
          keytool \
          -genkey -v \
          -storetype PKCS12 \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass '${{ secrets.INJI_ANDROID_RELEASE_STOREPASS }}' \
          -keypass '${{ secrets.INJI_ANDROID_RELEASE_STOREPASS }}' \
          -alias androidreleasekey \
          -keystore android/app/release.keystore \
          -dname "CN=io.mosip.residentapp,OU=,O=,L=,S=,C=US"

      - name: Export variables for keystore
        run: |
          cd android/app
          export RELEASE_KEYSTORE=release.keystore
          export RELEASE_KEYSTORE_ALIAS=androidreleasekey
          export RELEASE_KEYSTORE_PASSWORD='${{ secrets.INJI_ANDROID_RELEASE_STOREPASS }}'

      - name: Bump version code
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: android/app/build.gradle
          versionCode: ${{github.run_number}}

      - name: Run Build
        run: | 
          cd android
          ./gradlew :app:bundleNewlogicRelease
          # yes | sudo gem install bundler
          # yes | sudo fastlane install_plugins
          # fastlane test_android_build
        env:
          MIMOTO_HOST: ${{ github.event.inputs.backendServiceUrl }}
          APPLICATION_THEME: ${{ github.event.inputs.theme }}
          RELEASE_KEYSTORE: release.keystore 
          RELEASE_KEYSTORE_ALIAS: androidreleasekey
          RELEASE_KEYSTORE_PASSWORD: '${{secrets.INJI_ANDROID_RELEASE_STOREPASS}}'
      
      - name: Upload Artifact to Actions
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Inji-apk
          path: android/app/build/outputs/bundle/newlogicRelease/app-newlogic-release.aab
          retention-days: 10

      # - name: Publish to Play Store BETA
      #   id: publish
      #   uses: r0adkll/upload-google-play@v1
      #   with:
      #     serviceAccountJson: service_account.json - stored in secrets
      #     packageName: com.name.appname
      #     releaseFile: app/build/outputs/bundle/newlogicRelease/app-newlogic-release.aab
      #     track: beta
