name: Build When ever a Pull request is raised

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - ci-windows-android

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.20.0'

      - name: Install npm 
        run: |
          npm install
