# Android Build on Windows Runner via Fastlane

name: Android Build Pipeline - Windows

on:
  push:
    branches: [ci-windows-android] 


jobs:
  android_build_job:
    runs-on: [self-hosted, Windows, X64]

    env:
      KEYSTORE_PASSWORD: 'android'
      KEY_PASSWORD: 'android'
     

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
            node-version: '16.x'

      - name: Set environment variable
        uses: actions/set-env@v2
        with:
          ANDROID_HOME: C:\Android
          GRADLE_HOME: C:\ProgramData\chocolatey\lib\gradle\tools\gradle-8.1
          JAVA_HOME: C:\Program Files\Microsoft\jdk-11.0.18.10-hotspot\

      - name: ANDROID_HOME
        run: |
         echo $ANDROID_HOME
         echo $GRADLE_HOME
         echo $JAVA_HOME

      - name: Set PATH
        run: echo "sdk.dir=C:\\Android"> android/local.properties


      - name: Install npm dependencies
        run: |
            npm install
      

      - name: Build APK
        run: |
           pwd
           cd android
           ./gradlew :app:assembleMosipRelease
      
      
      - name: Upload Artifact file
        run: |
          mkdir apk
          cp inji/android/app/build/outputs/apk/release/app-release.apk apk/
