name: Android Build

on:
  push:
    branches:
      - ci-windows-android

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    steps:
        - uses: actions/checkout@v3.1.0

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'

        - name: Install dependencies
          run: npm install