name: Testing my workflow file 1.2

env:
  JAVA_HOME: ${{ env.JAVA_HOME }}
  ANDROID_HOME: ${{ env.ANDROID_HOME }}
  PATH: ${{ env.PATH }}:${{ env.JAVA_HOME }}/bin:${{ env.ANDROID_HOME }}/tools:${{ env.ANDROID_HOME }}/platform-tools

on:
  push:
    branches:
      - ci-linux-android
    tags:
      - '*'

jobs:
  build-android:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android-sdk@v2
        with:
          sdk-version: 'latest'
        
      - name: Accept Android licenses
        run: $ANDROID_HOME/tools/bin/sdkmanager --licenses
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }} 

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Create .env.local file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.local > android/local.properties

      - name: Setup branch and env 
        run: |
          # Strip git ref prefix from version
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV   
