# Android Build on Windows Runner via Fastlane

name: Android Build Pipeline - Windows

on:
  push:
    branches: [ci-windows-android] 


jobs:
  android_build_job:
    runs-on: [self-hosted, Windows, X64]

    env:
      KEYSTORE_PASSWORD: 'android'
      KEY_PASSWORD: 'android'

    steps:
     
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0

        with:
          path: inji

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install Dependencies
        run: |
          choco install openjdk --version=11.0
          choco install nodejs --version=16.17.0
          npm install -g npm@8.19.3
       
        working-directory: inji

      - name: Create .env.local file
        run: |
          echo "" > .env.local > android/local.properties

      - name: Run Fastlane
        run: |
          fastlane android_build
       
        working-directory: inji

      - name: Upload Artifact file
        run: |
          mkdir apk
          cp inji/android/app/build/outputs/apk/release/app-release.apk apk/
       
        working-directory: inji
