name: Testing my workflow file 1.1

on:
  push:
    branches:
      - ci-linux-android
    tags:
      - '*'

jobs:
  build-android:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Create .env.local file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.local > android/local.properties

      - name: Setup branch and env 
        run: |
          # Strip git ref prefix from version
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV   

      - name: Build App Newlogic Release
        run: |
          cd android
          ./gradlew :app:assembleNewlogicRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: output
          path: android/app/build/outputs/apk/newlogic/release/
          retention-days: 1