# Android Build on Windows Runner via Fastlane

name: Android Build Pipeline - Windows

on:
  push:
    branches: [ci-windows-android] 


jobs:
  android_build_job:
    runs-on: [self-hosted, Windows, X64]

    env:
      KEYSTORE_PASSWORD: 'android'
      KEY_PASSWORD: 'android'

    steps:
     
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'


      - name: Install npm dependencies
        # shell: pwsh
        run: |
          npm install
        working-directory: inji
        

      - name: Create .env.local file
        run: |
          echo "" > .env.local > android/local.properties

      - name: Run Fastlane
        run: |
          fastlane android_build
       
        working-directory: inji

      - name: Upload Artifact file
        run: |
          mkdir apk
          cp inji/android/app/build/outputs/apk/release/app-release.apk apk/
       
        working-directory: inji
