name: Inji iOS build

env:
    backendServiceDefaultUrl: https://api.qa-121.mosip.net

  # Allows you to run this workflow manually from the Actions a tab
on:
  push:
     branches: [ci-ios]
          
  # workflow_dispatch:
  #   inputs:
  #     backendServiceUrl:
  #       description: 'Backend service URL'
  #       required: true
  #       default: 'https://api.qa-121.mosip.net'
  #       type: string
  #     theme:
  #       description: 'Application Theme'
  #       required: true
  #       default: 'orange'
  #       type: choice
  #       options:
  #         - orange
  #         - purple
jobs:
  build_ios:
    name: Deploying to Testflight
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: Install npm dependencies
        run: |
          npm install
        
      - name: Install Pod
        run: |
          cd ios
          pod install
        
      - name: Deploy iOS Beta to TestFlight
        run: |
          cd ios
          fastlane beta
          
        env:
          APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
          DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
          DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
          FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
          TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
          APPLE_KEY_ID: '${{ secrets.APPLE_KEY_ID }}'
          APPLE_ISSUER_ID: '${{ secrets.APPLE_ISSUER_ID }}'
          APPLE_KEY_CONTENT: '${{ secrets.APPLE_KEY_CONTENT }}'