name: 'Delete old artifacts'
on:
  workflow_dispatch:

jobs:
  delete-artifacts:
    uses: mosip/kattu/.github/workflows/clear-artifacts.yml@master
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACTION_PAT }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}